default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *default
  database: splastage_development

test:
  <<: *default
  database: splastage_test

production:
  <<: *default
  database: splastage_production
